kind: pipeline
type: docker
name: deploy papierpain

platform:
  os: linux
  arch: arm

trigger:
  branch:
    - master

steps:
  - name: initialisation
    pull: if-not-exists
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: HOST_PAIN
      username:
        from_secret: LOGIN_PAIN
      password: 
        from_secret: PWD_PAIN
      port: 7137
      script:
        - cd /var/www/html
        - rm -rf papierpain

  - name: deploy
    pull: if-not-exists
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: HOST_PAIN
      username:
        from_secret: LOGIN_PAIN
      password: 
        from_secret: PWD_PAIN
      port: 7137
      command_timeout: 2m
      target: /var/www/html/papierpain
      source: ./*
